### ISSUE TITLE
Resizing window to narrow profile offsets connection lines

### ISSUE THREAD

**Issue by b-erv** [InfiniteAmmoInc/Yarn#77]
When the Yarn window is close to or at its minimum width, any lines between nodes get shunted to one side and no longer line up. Happening for me consistently at various resolutions and display magnification settings.
![resize](https://user-images.githubusercontent.com/17258819/43918439-15efe6d4-9be1-11e8-9d2a-435489c3c8b5.gif)

**Comment by blurymind** [comment]
Does that also happen in the electron version?

Also can you please zip the file you have open and attach it to your post
here

**Comment by b-erv** [comment]
Yes, the same behaviour is occurring for me across versions. Additionally, it happens the same way with all .yarn files, even newly-created ones. Such as here:
[demo.yarn.txt](https://github.com/InfiniteAmmoInc/Yarn/files/2279529/demo.yarn.txt)

**Comment by julsam** [comment]
I've been able to reproduce the issue with the NWjs build (aka master) but not with the electron build.

Maybe it has to do with this? Not sure.
```css
/* --- MEDIA --- */

@media (max-width: 830px) {
	.app-search {
		position: relative;
		float: left;
	}
	.app-menu {
		position: relative;
		float: right;
		margin-top: 20px;
	}
}
```
